---
sidebar: sidebar 
permalink: task-s3-enable-data-services.html 
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment 
summary: BlueXP에서 S3 버킷을 발견한 후 NetApp 데이터 서비스를 사용하여 백업, 계층화, 분류 및 데이터 동기화를 수행할 수 있습니다. 
---
= S3 버킷과 NetApp 데이터 서비스 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에서 S3 버킷을 발견한 후 NetApp 데이터 서비스를 사용하여 백업, 계층화, 분류 및 데이터 동기화를 수행할 수 있습니다.

* BlueXP 백업 및 복구 * 를 사용하여 사내 ONTAP 및 Cloud Volumes ONTAP 시스템의 데이터를 S3 오브젝트 스토리지로 백업합니다.
+
시작하려면 Canvas로 이동하여 Amazon S3 작업 환경에서 온-프레미스 ONTAP 또는 Cloud Volumes ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["ONTAP 데이터를 Amazon S3 스토리지로 백업하는 방법에 대해 자세히 알아보십시오"^].

* BlueXP 계층화 * 를 사용하여 비활성 데이터를 사내 ONTAP 클러스터에서 S3 오브젝트 스토리지로 계층화할 수 있습니다.
+
시작하려면 Canvas로 이동하여 Amazon S3 작업 환경에 온-프레미스 ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["ONTAP 데이터를 Amazon S3 스토리지로 계층화하는 방법에 대해 자세히 알아보십시오"^].

* BlueXP 복사 및 동기화 * 를 사용하여 S3 버킷과 데이터를 동기화할 수 있습니다.
+
시작하려면 Canvas로 이동하여 대상 작업 환경에 소스 작업 환경을 끌어다 놓습니다. Amazon S3 작업 환경은 소스 또는 타겟이 될 수 있습니다.

+
또한 Amazon S3 작업 환경을 선택하고 서비스 패널에서 * 복사 및 동기화 * 를 클릭하여 S3 버킷과 데이터를 동기화할 수 있습니다.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["BlueXP 복사 및 동기화 서비스에 대해 자세히 알아보십시오"^].

* BlueXP 분류 * 를 사용하여 S3 버킷을 스캔하여 개인 데이터와 민감한 데이터를 확인합니다. BlueXP 분류는 NetApp 솔루션용으로 생성되었는지에 관계없이 고객의 모든 버킷을 스캔할 수 있습니다.
+
시작하려면 Amazon S3 작업 환경을 선택하고 서비스 패널의 * 분류 * 섹션에서 적절한 옵션을 선택하여 S3 버킷 스캔을 시작합니다.

+
https://docs.netapp.com/us-en/bluexp-classification/task-scanning-s3.html["BlueXP 분류 서비스에 대해 자세히 알아보십시오"^].


