---
sidebar: sidebar 
permalink: task-s3-enable-data-services.html 
keywords: s3 buckets, s3 storage, s3 working environment, amazon s3 buckets, amazon s3 working environment 
summary: BlueXP에서 S3 버킷을 발견한 후 NetApp 데이터 서비스를 사용하여 백업, 계층화, 분류 및 데이터 동기화를 수행할 수 있습니다. 
---
= S3 버킷과 NetApp 데이터 서비스 사용
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에서 S3 버킷을 발견한 후 NetApp 데이터 서비스를 사용하여 백업, 계층화, 분류 및 데이터 동기화를 수행할 수 있습니다.

* 클라우드 백업 * 을 사용하여 사내 ONTAP 및 Cloud Volumes ONTAP 시스템의 데이터를 S3 오브젝트 스토리지로 백업할 수 있습니다.
+
시작하려면 Canvas로 이동하여 Amazon S3 작업 환경에서 온-프레미스 ONTAP 또는 Cloud Volumes ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-ontap-backup-to-cloud.html["ONTAP 데이터를 Amazon S3 스토리지로 백업하는 방법에 대해 자세히 알아보십시오"^].

* Cloud Tiering * 을 사용하여 사내 ONTAP 클러스터에서 S3 오브젝트 스토리지로 비활성 데이터를 계층화할 수 있습니다.
+
시작하려면 Canvas로 이동하여 Amazon S3 작업 환경에 온-프레미스 ONTAP 작업 환경을 끌어다 놓습니다.

+
https://docs.netapp.com/us-en/cloud-manager-tiering/task-tiering-onprem-aws.html["ONTAP 데이터를 Amazon S3 스토리지로 계층화하는 방법에 대해 자세히 알아보십시오"^].

* Cloud Sync * 를 사용하여 S3 버킷 간에 데이터를 동기화합니다.
+
시작하려면 Canvas로 이동하여 대상 작업 환경에 소스 작업 환경을 끌어다 놓습니다. Amazon S3 작업 환경은 소스 또는 타겟이 될 수 있습니다.

+
또한 Amazon S3 작업 환경을 선택하고 서비스 패널에서 * 데이터 동기화 * 를 클릭하여 S3 버킷과 데이터를 동기화할 수 있습니다.

+
https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["Cloud Sync 서비스에 대해 자세히 알아보십시오"^].

* Cloud Data Sense * 를 사용하여 S3 버킷에서 개인 및 중요 데이터를 검색할 수 있습니다. Cloud Data Sense는 NetApp 솔루션용으로 만들어졌는지에 관계없이 고객의 모든 버킷을 스캔할 수 있습니다.
+
시작하려면 Amazon S3 작업 환경을 선택하고 서비스 패널의 * 분류 * 섹션에서 적절한 옵션을 선택하여 S3 버킷 스캔을 시작합니다.

+
https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-s3.html["클라우드 데이터 감지 서비스에 대해 자세히 알아보십시오"^].


